runtime: nodejs18
env_variables:
  DATABASE_URL: "mysql://root:123456@localhost:3306/bookdb"
  AUTH0_JWK_URI: https:///dev-q0n7p4145fanb802.us.auth0.com/.well-known/jwks.json
  AUTH0_AUDIENCE: https://apt.read
  AUTH0_ISSUER: https:///dev-q0n7p4145fanb802.us.auth0.com/
  PORT: 8080
